
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/spring-boot/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-c93ea54ea3e08eaa2a17640d5d2b3e60264c1a9c
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            